name: Deploy Ubuntu Server Project

on:
  push:
    branches:
      - main  # Change to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Add SSH private key to agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          APP_DIR: ${{ secrets.APP_DIR }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PWD_SUDO: ${{ secrets.PWD_SUDO }}
        run: |
          sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
          cd $APP_DIR &&
          echo $PWD_SUDO | sudo -S git remote set-url origin git@github.com:Duplexificate/korutama.git
          sudo git pull origin main &&
          sudo npm install &&
          sudo npm run build
          "
